language: node_js
node_js:
        - "0.11"
        - "0.10"

python:
        - "2.7"

services:
        - mongodb

install:
        - npm install -g phantomjs
        - npm install weak
        - npm install

script: npm test
